starcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('stars/', views.stars_index, name='index'),
    path('stars/<int:star_id>/', views.stars_detail, name='detail'),
    path('stars/create/', views.StarCreate.as_view(), name='stars_create'),
    path('stars/<int:pk>/update/', views.StarUpdate.as_view(), name='stars_update'),
    path('stars/<int:pk>/delete/', views.StarDelete.as_view(), name='stars_delete'),
    path('stars/<int:star_id>/add_photo', views.add_photo, name='add_photo'),
    path('stars/<int:star_id>/add_viewing/', views.add_viewing, name='add_viewing'),
    path('stars/<int:star_id>/assoc_observatory/<int:observatory_id>/', views.assoc_observatory, name='assoc_observatory'),
    path('stars/<int:star_id>/unassoc_observatory/<int:observatory_id>/', views.unassoc_observatory, name='unassoc_observatory'),
    path('observatories/', views.ObservatoryList.as_view(), name='observatories_index'),
    path('observatories/<int:pk>/', views.ObservatoryDetail.as_view(), name='observatories_detail'),
    path('observatories/create/', views.ObservatoryCreate.as_view(), name='observatories_create'),
    path('observatories/<int:pk>/update/', views.ObservatoryUpdate.as_view(), name='observatories_update'),
    path('observatories/<int:pk>/delete/', views.ObservatoryDelete.as_view(), name='observatories_delete'),
    path('accounts/signup', views.signup, name='signup'),
]

starcollector/starcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

starcollector/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.
VISIBILITY = (
    ('C', 'Clear'),
    ('P', 'Partial'),
    ('O', 'Obscured')
)


class Observatory(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('observatories_detail', kwargs={'pk': self.id})


class Star(models.Model):
    name = models.CharField(max_length=100)
    type_of_star = models.CharField(max_length=100)
    distance = models.FloatField()
    mass = models.FloatField()
    observatories = models.ManyToManyField(Observatory)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'star_id': self.id})


class Viewing(models.Model):
    date = models.DateField("Viewing date")
    time = models.TimeField(
        blank=True,
        null=True
    )
    visibility = models.CharField(
        max_length=1,
        choices=VISIBILITY,
        default=VISIBILITY[0][0]
    )

    star = models.ForeignKey(Star, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_visibility_display()} on {self.date} at {self.time}"
    
    class Meta:
        ordering = ['-date']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    star = models.ForeignKey(Star, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for star_id: {self.star_id}@{self.url}"

starcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Viewing


class ViewingForm(ModelForm):
    class Meta:
        model = Viewing
        fields = ['date', 'time', 'visibility']

starcollector/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
from .models import Star, Observatory, Photo
from .forms import ViewingForm


S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'starcollector-chung972'

# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

@login_required
def stars_index(request):
    stars = Star.objects.filter(user=request.user)
    return render(request, 'stars/index.html', {'stars': stars})


@login_required
def stars_detail(request, star_id):
    star = Star.objects.get(id=star_id)
    observatories_star_unviewable_from = Observatory.objects.exclude(
        id__in=star.observatories.all().values_list('id'))
    viewing_form = ViewingForm()
    return render(request, 'stars/detail.html', {
        'star': star,
        'viewing_form': viewing_form,
        # the key for unassociated observatories is important; esp when printing out (using {{}}} ) in the details.html page
        'observatories': observatories_star_unviewable_from
    })


class StarCreate(LoginRequiredMixin, CreateView):
    model = Star
    fields = ['name', 'type_of_star', 'distance', 'mass']
    success_url = '/stars/'

    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user
        # Let the CreateView do its job as usual
        return super().form_valid(form)


class StarUpdate(LoginRequiredMixin, UpdateView):
    model = Star
    fields = ['type_of_star', 'distance', 'mass']


class StarDelete(LoginRequiredMixin, DeleteView):
    model = Star
    success_url = '/stars/'


@login_required
def add_viewing(request, star_id):
    form = ViewingForm(request.POST)
    if form.is_valid():
        new_viewing = form.save(commit=False)
        new_viewing.star_id = star_id
        new_viewing.save()
    return redirect('detail', star_id=star_id)


class ObservatoryList(LoginRequiredMixin, ListView):
    model = Observatory


class ObservatoryDetail(LoginRequiredMixin, DetailView):
    model = Observatory


class ObservatoryCreate(LoginRequiredMixin, CreateView):
    model = Observatory
    fields = '__all__'


class ObservatoryUpdate(LoginRequiredMixin, UpdateView):
    model = Observatory
    fields = ['name', 'location']


class ObservatoryDelete(LoginRequiredMixin, DeleteView):
    model = Observatory
    success_url = '/observatories/'


@login_required
def assoc_observatory(request, star_id, observatory_id):
    Star.objects.get(id=star_id).observatories.add(observatory_id)
    return redirect('detail', star_id=star_id)


@login_required
def unassoc_observatory(request, star_id, observatory_id):
    Star.objects.get(id=star_id).observatories.remove(observatory_id)
    return redirect('detail', star_id=star_id)


@login_required
def add_photo(request, star_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to star_id or star (if you have a star object)
            photo = Photo(url=url, star_id=star_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', star_id=star_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

starcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Star Collector</h1>
<hr />
<p>Hire the Star Collector!</p>

{% endblock %}

starcollector/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Star Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Star Collector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'observatories_create' %}">Add an Observatory</a></li>
                    <li><a href="{% url 'observatories_index' %}">View All Observatories</a></li>
                    <li><a href="{% url 'stars_create' %}">Add Star</a></li>
                    <li><a href="{% url 'index' %}">View All My Stars</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	 <footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2019 Star Collector &nbsp;</div>
    </footer>
</body>
</html>

starcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

starcollector/main_app/templates/main_app/observatory_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Observatory</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'observatories_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

starcollector/main_app/templates/main_app/observatory_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Observatory Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ observatory.name }}</span>
        <p>Location: {{ observatory.location }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'observatories_update' observatory.id %}">Edit</a>
        <a href="{% url 'observatories_delete' observatory.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

starcollector/main_app/templates/main_app/observatory_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Observatory</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

starcollector/main_app/templates/main_app/observatory_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Observatory List</h1>

{% for observatory in observatory_list %}
  <a href="{% url 'observatories_detail' observatory.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ observatory.name }}</span>
            <p>Location: {{ observatory.location }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

starcollector/main_app/templates/main_app/star_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Star</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' star.id %}">Cancel</a>
  </form>
{% endblock %}

starcollector/main_app/templates/main_app/star_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Star</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

starcollector/main_app/templates/stars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Star Details</h1>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ star.name }}</span>
                <p>Spectral Type: {{ star.type_of_star }}</p>
                <p>Distance from Earth: {{ star.distance }} lightyears</p>
                {% if star.mass > 1 %}
                <p>Mass: {{ star.mass }} M (solar mass)</p>
                {% else %}
                <p>Mass: Lighter than the Sun</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'stars_update' star.id %}">Edit</a>
                <a href="{% url 'stars_delete' star.id %}">Delete</a>
            </div>
        </div>
        {% for photo in star.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form action="{% url 'add_photo' star.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <input type="submit" class="btn" value="Upload Photo">
        </form>
    </div>

    <div class="col s6">
        <form action="{% url 'add_viewing' star.id %}" method="POST">
            {% csrf_token %}
            {{ viewing_form.as_p }}
            <input type="submit" class="btn" value="Add Viewing">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Visibility</th>
                </tr>
            </thead>
            <tbody>
                {% for viewing in star.viewing_set.all %}
                <tr>
                    <td>{{viewing.date}}</td>
                    <td>{{viewing.time}}</td>
                    <td>{{viewing.get_visibility_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ star.name }} can be viewed from:</h3>
        {% if star.observatories.count %}
        {% for observatory in star.observatories.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ observatory.name }} at {{observatory.location}}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'unassoc_observatory' star.id observatory.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Remove</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No observatories selected</h5>
        {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    <div class="col s6">
        <h3>Available Observatories</h3>
        {% if observatories.count %}
        {% for observatory in observatories.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ observatory.name }} at {{ observatory.location }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_observatory' star.id observatory.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{star.observatory}} Viewable from all available observatories</h5>
        {% endif %}
    </div>
</div>
<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    var timeEl = document.getElementById('id_time');
    M.Timepicker.init(timeEl, {
        defaultTime: '00:00',
        twelveHour: false,
        autoClose: true
    });

    var selectEl = document.getElementById('id_visibility');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

starcollector/main_app/templates/stars/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Star List</h1>

{% for star in stars %}
    <div class="card">
        <a href="{% url 'detail' star.id %}">
            <div class="card-content">
                <span class="card-title">{{ star.name }}</span>
                <p>Spectral Type: {{ star.type_of_star }}</p>
                <p>Distance from Earth: {{ star.distance }} lightyears</p>
                {% if star.mass > 1 %}
                    <p>Mass: {{ star.mass }} M (solar mass)</p>
                {% else %}
                    <p>Mass: Lighter than the Sun</p>
                {% endif %}
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}